### ISSUE TITLE
Have you tried Transformer Architecture Search

### ISSUE THREAD

**Issue by kilickaya** [yuny220/NAR-Former#1]
Hello,

Congrats on your awesome work. A quick question. have you tried your model for Transformer Architecture Search as well? https://github.com/decemberzhou/TF_TAS

**Comment by yuny220** [comment]
> Hello,
> 
> Congrats on your awesome work. A quick question. have you tried your model for Transformer Architecture Search as well? https://github.com/decemberzhou/TF_TAS

Thanks for your attention to our work. So far, we have not tried to apply the model to Transformer Architecture Search.
